### ISSUE TITLE
[Bug] duplicating linked resources returns incorrect data

### ISSUE THREAD

**Issue by YuanRamirez** [ElfFriend-DnD/foundryvtt-link-item-resource-5e#8] opened 2022-04-18 22:14 UTC
**Problem**
Calling `update` on an actor with `duplicate`d ActorData resets linked resources to whatever they were before the links were established.

**Expected Behavior**
Linked resources should survive duplication.

**Steps to reproduce**
1. set up an actor with linked resources
3. run the following code:
```js
let a = game.actors.getName("Akra (Dragonborn Cleric)");
let aData = duplicate(a.data);
a.update(aData);
```

**Additional context/thoughts**
Note that the code above, in theory, shouldn't do anything at all. You will notice, however, that the previously linked resources (and the respective item charges etc) are now all set to 0 (or whatever the resources were before linking them).
`aData` contains the original resource setup (before linking), but why?
Checking `a.data.data.resources.primary` before pushing the update shows the values the way they're being displayed on the character sheet so that
```js
let a = game.actors.getName("Akra (Dragonborn Cleric)");
console.log(a.data.data.resources.primary);
let aData = duplicate(a.data);
console.log(aData.data.resources.primary);
```
spits out 
```js
{label: 'Breath Weapon', value: 1, max: 1, sr: true, lr: true}
{value: null, max: null, sr: false, lr: false, label: ''}
```

As a workaround, one can `delete` the resource property before updating but that seems inelegant because it should be unnecessary. Also, problems arise if the changes being pushed by the update actually involve the linked resources.

**Environment**
Observed on Foundry 9.268, DnD5e 1.5.7
on a blank world with no other active modules (except the dependency "libWrapper" ofc).

**Comment by akrigline** [comment] 2022-04-18 22:50
Do me a favor and try running `a.prepareData()` on the duplicate actor, then see what the output of the resource fields are

**Comment by YuanRamirez** [comment] 2022-04-19 00:57
`prepareData` does seem to do the trick!

```js
let a = game.actors.getName("Akra (Dragonborn Cleric)");
let aDup = duplicate(a);
aDup.prepareData; // prepareData() returns a TypeError "is not a function"
a.update(aDup.data);
```

As you can see, I do have to duplicate the entire actor, though. That's at least noteworthy. Community macros and such tend to duplicate the data of whatever is being updated. An uninformed user might end up trying to use macros that don't work as intended.

**Comment by akrigline** [comment] 2022-04-19 02:51
Interesting... It's wierd to me that macros use a duplicate of the actor's data instead of directly updating the data of the original.

This isn't something I can really fix in this module. The module patches the `prepareData` method for Actors in the 5e system to do that substitution. The `duplicate` utility function I guess is a standin for getting the actor data in its raw form (I would recommend using `a.toJSON()` or `a.toObject()` for that by the way).

Either way, glad this helped you and maybe it will help whoever else in the future that runs into this problem.

**Closed by akrigline** 2022-04-19 02:51 UTC
